#!/usr/bin/env bash
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(CDPATH= cd -- "${script_dir}/.." && pwd -P)"
build_dir="${repo_root}/build"
gate_dir="${build_dir}/gates"
log_dir="${build_dir}/logs"
observed_dir="${build_dir}/toolchain"
gate_file="${gate_dir}/P0.1.status"
fingerprint_file="${gate_dir}/P0.1.sources.sha256"
log_file="${log_dir}/doctor.log"
lock_file="${repo_root}/toolchain.lock"

mkdir -p "${gate_dir}" "${log_dir}" "${observed_dir}"
rm -f -- "${gate_file}" "${fingerprint_file}"
exec > >(tee "${log_file}") 2>&1

outcome="FAIL"

write_gate() {
  local status="$1"
  local temporary
  temporary="$(mktemp "${gate_dir}/.P0.1.status.XXXXXX")"
  printf '%s\n' "${status}" >"${temporary}"
  mv -f -- "${temporary}" "${gate_file}"
}

finish() {
  local status=$?
  if [[ ${status} -ne 0 && ! -f "${gate_file}" ]]; then
    write_gate "${outcome}"
  fi
}
trap finish EXIT

fail() {
  outcome="FAIL"
  printf 'doctor: FAIL: %s\n' "$*" >&2
  exit 1
}

blocked() {
  outcome="BLOCKED"
  printf 'doctor: BLOCKED: %s\n' "$*" >&2
  exit 2
}

write_fingerprint() {
  local temporary
  temporary="$(mktemp "${gate_dir}/.P0.1.sources.sha256.XXXXXX")"
  if ! python3 "${repo_root}/scripts/evidence.py" --source-fingerprint >"${temporary}"; then
    rm -f -- "${temporary}"
    fail "could not fingerprint the checked repository inputs"
  fi
  mv -f -- "${temporary}" "${fingerprint_file}"
}

require_command() {
  local command_name="$1"
  command -v "${command_name}" >/dev/null 2>&1 \
    || blocked "required command is unavailable: ${command_name}"
}

read_assignment() {
  local key="$1"
  local file="$2"
  awk -F= -v wanted="${key}" '$1 == wanted { value = substr($0, index($0, "=") + 1); count += 1 } END { if (count == 1) print value; else exit 1 }' "${file}"
}

resolve_executable() {
  local configured="$1"
  local local_candidate="$2"
  local path_name="$3"
  local resolved

  if [[ -n "${configured}" ]]; then
    if [[ "${configured}" == */* ]]; then
      [[ -x "${configured}" ]] || return 1
      resolved="${configured}"
    else
      resolved="$(command -v "${configured}")" || return 1
    fi
  elif [[ -x "${local_candidate}" ]]; then
    resolved="${local_candidate}"
  else
    resolved="$(command -v "${path_name}")" || return 1
  fi

  readlink -f -- "${resolved}"
}

write_observed() {
  local name="$1"
  local value="$2"
  local destination="${observed_dir}/${name}"
  local temporary
  temporary="$(mktemp "${observed_dir}/.${name}.XXXXXX")"
  printf '%s\n' "${value}" >"${temporary}"
  mv -f -- "${temporary}" "${destination}"
}

for command_name in awk git grep mktemp mv nm python3 readlink sed sha256sum tee uname; do
  require_command "${command_name}"
done

[[ "$(uname -s)" == "Linux" ]] || blocked "P0 currently supports Linux only"
[[ -f "${lock_file}" ]] || blocked "missing toolchain.lock"

declare -A lock=()
while IFS='=' read -r key value; do
  [[ -n "${key}" ]] || continue
  [[ "${key}" =~ ^[A-Z0-9_]+$ ]] || fail "invalid key in toolchain.lock: ${key}"
  [[ -z "${lock[${key}]+present}" ]] || fail "duplicate key in toolchain.lock: ${key}"
  lock["${key}"]="${value}"
done <"${lock_file}"

[[ ${#lock[@]} -eq 7 ]] || fail "toolchain.lock must contain exactly seven assignments"
[[ "${lock[PEEL_TOOLCHAIN_SCHEMA]:-}" == "1" ]] || fail "unexpected toolchain schema"
[[ "${lock[FSTAR_TAG]:-}" == "v2026.07.24" ]] || fail "unexpected F* tag pin"
[[ "${lock[FSTAR_COMMIT]:-}" == "60f60c05ccdb2caa31eb52395d7818ba2df3904e" ]] || fail "unexpected F* commit pin"
[[ "${lock[KARAMEL_COMMIT]:-}" == "0a39f5a21cb79993c5780b5da24a2f28afbef634" ]] || fail "unexpected KaRaMeL commit pin"
[[ "${lock[Z3_VERSION]:-}" == "4.13.3" ]] || fail "unexpected Z3 version pin"
[[ "${lock[OCAML_VERSION]:-}" == "4.14.2" ]] || fail "unexpected OCaml version pin"
[[ "${lock[KARAMEL_ENVIRONMENT_VARIABLE]:-}" == "KRML_EXE" ]] || fail "KaRaMeL must be selected through KRML_EXE"

caller_fstar="${FSTAR_EXE:-}"
caller_krml="${KRML_EXE:-}"
caller_z3="${Z3_EXE:-}"
caller_ocamlc="${OCAMLC:-}"
if [[ -f "${repo_root}/.toolchain/env" ]]; then
  # This file is generated by the pinned bootstrap script and contains paths only.
  # shellcheck disable=SC1091
  source "${repo_root}/.toolchain/env"
fi
[[ -n "${caller_fstar}" ]] && FSTAR_EXE="${caller_fstar}"
[[ -n "${caller_krml}" ]] && KRML_EXE="${caller_krml}"
[[ -n "${caller_z3}" ]] && Z3_EXE="${caller_z3}"
[[ -n "${caller_ocamlc}" ]] && OCAMLC="${caller_ocamlc}"

fstar_exe="$(resolve_executable "${FSTAR_EXE:-}" "${repo_root}/.toolchain/bin/fstar.exe" fstar.exe)" \
  || blocked "exact F* executable is unavailable; run scripts/bootstrap-toolchain.sh explicitly"
krml_exe="$(resolve_executable "${KRML_EXE:-}" "${repo_root}/.toolchain/bin/krml" krml)" \
  || blocked "KRML_EXE does not resolve to an executable"
z3_exe="$(resolve_executable "${Z3_EXE:-}" "${repo_root}/.toolchain/bin/z3" z3)" \
  || blocked "Z3 ${lock[Z3_VERSION]} is unavailable"
cc_exe="$(resolve_executable "${CC:-}" "" cc)" \
  || blocked "C compiler is unavailable"
python_exe="$(resolve_executable "${PYTHON:-}" "" python3)" \
  || blocked "Python 3 is unavailable"

manifest_ocamlc=""
if [[ "${fstar_exe}" == "${repo_root}/.toolchain/"* ]]; then
  manifest_file="${repo_root}/.toolchain/manifest.env"
  archive_file="${repo_root}/.toolchain/downloads/fstar-v2026.07.24-Linux-x86_64.tar.gz"
  source_archive_file="${repo_root}/.toolchain/downloads/fstar-v2026.07.24-src.tar.gz"
  opam_file="${repo_root}/.toolchain/downloads/opam-2.5.2-x86_64-linux"
  [[ -f "${manifest_file}" ]] || blocked "local toolchain provenance manifest is missing"
  [[ -f "${archive_file}" ]] || blocked "recorded F* release archive is missing"
  [[ -f "${source_archive_file}" ]] || blocked "recorded F* source archive is missing"
  [[ -f "${opam_file}" ]] || blocked "recorded opam binary is missing"
  manifest_fstar="$(read_assignment FSTAR_EXE "${manifest_file}")" \
    || blocked "toolchain manifest lacks its F* executable path"
  manifest_krml="$(read_assignment KRML_EXE "${manifest_file}")" \
    || blocked "toolchain manifest lacks its KaRaMeL executable path"
  manifest_z3="$(read_assignment Z3_EXE "${manifest_file}")" \
    || blocked "toolchain manifest lacks its Z3 executable path"
  manifest_ocamlc="$(read_assignment OCAMLC "${manifest_file}")" \
    || blocked "toolchain manifest lacks its OCaml executable path"
  manifest_fstar="$(resolve_executable "${manifest_fstar}" "" fstar.exe)" \
    || blocked "manifest F* executable is unavailable"
  manifest_krml="$(resolve_executable "${manifest_krml}" "" krml)" \
    || blocked "manifest KaRaMeL executable is unavailable"
  manifest_z3="$(resolve_executable "${manifest_z3}" "" z3)" \
    || blocked "manifest Z3 executable is unavailable"
  [[ "${fstar_exe}" == "${manifest_fstar}" ]] \
    || fail "resolved F* executable is not the source-built manifest executable"
  [[ "${krml_exe}" == "${manifest_krml}" ]] \
    || fail "resolved KaRaMeL executable is not the source-built manifest executable"
  [[ "${z3_exe}" == "${manifest_z3}" ]] \
    || fail "resolved Z3 executable is not the manifest solver"
  [[ "$(read_assignment FSTAR_TAG "${manifest_file}")" == "${lock[FSTAR_TAG]}" ]] \
    || fail "toolchain manifest has the wrong F* tag"
  [[ "$(read_assignment FSTAR_COMMIT "${manifest_file}")" == "${lock[FSTAR_COMMIT]}" ]] \
    || fail "toolchain manifest has the wrong F* commit"
  [[ "$(read_assignment KARAMEL_COMMIT "${manifest_file}")" == "${lock[KARAMEL_COMMIT]}" ]] \
    || fail "toolchain manifest has the wrong KaRaMeL commit"
  [[ "$(read_assignment Z3_VERSION "${manifest_file}")" == "${lock[Z3_VERSION]}" ]] \
    || fail "toolchain manifest has the wrong Z3 version"
  [[ "$(read_assignment OCAML_VERSION "${manifest_file}")" == "${lock[OCAML_VERSION]}" ]] \
    || fail "toolchain manifest has the wrong OCaml pin"
  build_mode="$(read_assignment FSTAR_BUILD_MODE "${manifest_file}")" \
    || blocked "toolchain manifest lacks the F* build mode"
  [[ "${build_mode}" == "source" ]] || fail "the installed F* executable was not source-built"
  fstar_build_ocaml="$(read_assignment FSTAR_BUILD_OCAML_VERSION "${manifest_file}")" \
    || blocked "toolchain manifest lacks F* build-compiler provenance"
  karamel_build_ocaml="$(read_assignment KARAMEL_BUILD_OCAML_VERSION "${manifest_file}")" \
    || blocked "toolchain manifest lacks KaRaMeL build-compiler provenance"
  [[ "${fstar_build_ocaml}" == "${lock[OCAML_VERSION]}" ]] \
    || fail "F* was not built with locked OCaml ${lock[OCAML_VERSION]}"
  [[ "${karamel_build_ocaml}" == "${lock[OCAML_VERSION]}" ]] \
    || fail "KaRaMeL was not built with locked OCaml ${lock[OCAML_VERSION]}"
  archive_digest="$(read_assignment FSTAR_ARCHIVE_SHA256 "${manifest_file}")" \
    || blocked "toolchain manifest lacks the release archive digest"
  archive_url="$(read_assignment FSTAR_ARCHIVE_URL "${manifest_file}")" \
    || blocked "toolchain manifest lacks the release archive URL"
  [[ "${archive_url}" == "https://github.com/FStarLang/FStar/releases/download/v2026.07.24/fstar-v2026.07.24-Linux-x86_64.tar.gz" ]] \
    || fail "toolchain manifest has an unexpected F* release source URL"
  [[ "${archive_digest}" == "640443f12887f56e1decafb5891f47a22a8587b39a4774e0a7c64b57404cece6" ]] \
    || fail "toolchain manifest has an unexpected F* release archive SHA-256"
  [[ "${archive_digest}" =~ ^[0-9a-f]{64}$ ]] || fail "invalid release archive SHA-256"
  printf '%s  %s\n' "${archive_digest}" "${archive_file}" | sha256sum --check --status \
    || fail "cached F* release archive does not match its recorded SHA-256"

  source_archive_url="$(read_assignment FSTAR_SOURCE_ARCHIVE_URL "${manifest_file}")" \
    || blocked "toolchain manifest lacks the F* source archive URL"
  source_archive_digest="$(read_assignment FSTAR_SOURCE_ARCHIVE_SHA256 "${manifest_file}")" \
    || blocked "toolchain manifest lacks the F* source archive digest"
  [[ "${source_archive_url}" == "https://github.com/FStarLang/FStar/releases/download/v2026.07.24/fstar-v2026.07.24-src.tar.gz" ]] \
    || fail "toolchain manifest has an unexpected F* source URL"
  [[ "${source_archive_digest}" == "cf883f8964239d6ad28f66b7824cec141f5b1714e5fb38b2a192044a8522b2f0" ]] \
    || fail "toolchain manifest has an unexpected F* source archive SHA-256"
  printf '%s  %s\n' "${source_archive_digest}" "${source_archive_file}" | sha256sum --check --status \
    || fail "cached F* source archive does not match its recorded SHA-256"

  opam_version="$(read_assignment OPAM_VERSION "${manifest_file}")" \
    || blocked "toolchain manifest lacks the opam version"
  opam_url="$(read_assignment OPAM_BINARY_URL "${manifest_file}")" \
    || blocked "toolchain manifest lacks the opam binary URL"
  opam_digest="$(read_assignment OPAM_BINARY_SHA256 "${manifest_file}")" \
    || blocked "toolchain manifest lacks the opam binary digest"
  [[ "${opam_version}" == "2.5.2" ]] || fail "toolchain manifest has an unexpected opam version"
  [[ "${opam_url}" == "https://github.com/ocaml/opam/releases/download/2.5.2/opam-2.5.2-x86_64-linux" ]] \
    || fail "toolchain manifest has an unexpected opam binary URL"
  [[ "${opam_digest}" == "edfca2630c373b44b7ee1c2f81cd8dcf67468d0db57d6c02158de553ac63dbd4" ]] \
    || fail "toolchain manifest has an unexpected opam binary SHA-256"
  printf '%s  %s\n' "${opam_digest}" "${opam_file}" | sha256sum --check --status \
    || fail "cached opam binary does not match its recorded SHA-256"
  [[ "$("${opam_file}" --version)" == "${opam_version}" ]] \
    || fail "cached opam binary did not report version ${opam_version}"
fi

fstar_version="$("${fstar_exe}" --version)" || fail "F* version command failed"
krml_version="$("${krml_exe}" -version)" || fail "KaRaMeL version command failed"
z3_version="$("${z3_exe}" --version)" || fail "Z3 version command failed"
cc_version="$("${cc_exe}" --version)" || fail "C compiler version command failed"
python_version="$("${python_exe}" --version 2>&1)" || fail "Python version command failed"

printf '%s\n' "${fstar_version}"
printf '%s\n' "${krml_version}"
printf '%s\n' "${z3_version}"

grep -Fqx "F* 2026.07.24" <<<"${fstar_version}" \
  || fail "F* did not report version 2026.07.24"
grep -Fqx "commit=${lock[FSTAR_COMMIT]}" <<<"${fstar_version}" \
  || fail "F* did not report commit ${lock[FSTAR_COMMIT]}"
grep -Fq "KaRaMeL version: ${lock[KARAMEL_COMMIT]}" <<<"${krml_version}" \
  || fail "KaRaMeL did not report commit ${lock[KARAMEL_COMMIT]}"
grep -Fq "Z3 version ${lock[Z3_VERSION]}" <<<"${z3_version}" \
  || fail "Z3 did not report version ${lock[Z3_VERSION]}"

located_z3="$("${fstar_exe}" --locate_z3 "${lock[Z3_VERSION]}")" \
  || fail "F* could not locate its selected Z3"
located_z3="$(resolve_executable "${located_z3}" "" z3)" \
  || fail "the Z3 selected by F* is not executable"
[[ "${located_z3}" == "${z3_exe}" ]] \
  || fail "F* is not using the Z3 executable validated by doctor"

observed_ocaml="$(sed -n 's/^compiler=OCaml //p' <<<"${fstar_version}")"
[[ -n "${observed_ocaml}" ]] || fail "F* did not report its OCaml compiler version"

write_observed fstar-exe.txt "${fstar_exe}"
write_observed krml-exe.txt "${krml_exe}"
write_observed z3-exe.txt "${z3_exe}"
write_observed cc-exe.txt "${cc_exe}"
write_observed python-exe.txt "${python_exe}"
write_observed fstar-version.txt "${fstar_version}"
write_observed karamel-version.txt "${krml_version}"
write_observed z3-version.txt "${z3_version}"
write_observed ocaml-version.txt "${observed_ocaml}"
write_observed python-version.txt "${python_version}"
write_observed c-compiler.txt "${cc_version}"

if [[ "${observed_ocaml}" != "${lock[OCAML_VERSION]}" ]]; then
  blocked "F* reports compiler=OCaml ${observed_ocaml}; the immutable pin requires ${lock[OCAML_VERSION]}"
fi

ocamlc_exe="$(resolve_executable "${OCAMLC:-}" "${repo_root}/.toolchain/bin/ocamlc" ocamlc)" \
  || blocked "OCaml compiler ${lock[OCAML_VERSION]} is unavailable"
if [[ -n "${manifest_ocamlc}" ]]; then
  manifest_ocamlc="$(resolve_executable "${manifest_ocamlc}" "" ocamlc)" \
    || blocked "manifest OCaml executable is unavailable"
  [[ "${ocamlc_exe}" == "${manifest_ocamlc}" ]] \
    || fail "resolved OCaml executable is not the manifest compiler"
fi
ocaml_version="$("${ocamlc_exe}" -version)" || fail "OCaml version command failed"
[[ "${ocaml_version}" == "${lock[OCAML_VERSION]}" ]] \
  || fail "ocamlc reports ${ocaml_version}; expected ${lock[OCAML_VERSION]}"
write_observed ocamlc-exe.txt "${ocamlc_exe}"

write_fingerprint
write_gate PASS
printf '%s\n' 'P0.1 PASS: exact locked toolchain resolved.'
